apiVersion: v1
kind: PersistentVolume
metadata:
  name: vude-pv
  namespace: rjamapax
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-storage
  nfs:
    path: /opt/vudenfs/vudedata
    server: 10.208.35.14
