apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vude-pvc
  namespace: rjamapax
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
